fixed bug following from introduction of parse_fakepdf in config.py
NNPDF/nnpdf pull request #1654
Opened 2022-12-23 11:32 UTC by comane

Because of the introduction of the parse_fakepdf method in config.py, the val corresponding to the "fakepdf" key of the datacuts dict in produce_fitunderlyinglaw function is not type str anymore but core.PDF. This leads to an error when running vp-comparefits:

[ERROR]: Bad configuration encountered:
Bad input type for parameter 'pdf': Value 'NNPDF40_nnlo_as_01180' is not of type str, but of type 'PDF'.

2022-12-24 17:35 UTC, Zaharid commented
Do we need to parse the pdf again or can we set it to the value we already get?

2022-12-25 14:18 UTC, RoyStegeman requested changes
Thanks for pointing this out. I agree with Zahari, I don't see why we need to parse it seperately in each function, in this case we should just use the pdf directly.

2022-12-27 09:54 UTC, comane commented
Thank you for the comments. The new commit should do so. The fakepdf stored in datacuts is taken instead of parsing it again.
There might be other issues with the config.produce_multiclosure_underlyinglaw() function but I don't know in which context this function is to be used.

2022-12-28 08:58 UTC, Zaharid commented on validphys2/src/validphys/config.py
> +            _, datacuts = self.parse_from_("fit", "closuretest", write=False)
```suggestion
            _, datacuts = self.parse_from_("fit", "closuretest", write=False)
```

2022-12-28 08:59 UTC, Zaharid approved these changes

2022-12-28 16:22 UTC, comane commented
> What problems are you anticipating? I guess that function would be used to calculate closure test estimators such as these: https://vp.nnpdf.science/5m-aHiGmRVGsOjeZ58AtyA==/ which are based on multiple fits (25 in this case) and to correctly evaluate these estimators the underlying law for each of the fits needs to have been the same.

I guess the problem could be that
`laws.add(closuretest_spec["fakepdf"])`
is adding a PDF object to the `laws` set instead of a string, therefore
`return self.parse_pdf(laws.pop())`
would give the same problem as above.

I think one could just do the following change:
`return laws.pop()`

2022-12-29 10:31 UTC, RoyStegeman commented
Did you try? I don't think it's a problem here because the `fakepdf` is obtained by reading  the `filter.yml` file directly (i.e. it's not parsed by reportengine and thus not placed in a namespace).

2023-01-03 08:30 UTC, comane commented
Yes, I agree with you. Thanks for the comment. I think with the last commit the branch can be merged

2023-01-03 10:00 UTC, RoyStegeman approved these changes
Looks good. Thanks for spotting this!

2023-01-03 12:19 UTC, merged

2023-01-03 12:19 UTC, Zaharid commented
Thanks both!