Implement LHCB_WENU_8TEV
NNPDF/nnpdf pull request #1889
Opened 2023-12-11 10:45 UTC by niclaurenti

2023-12-13 08:01 UTC, Radonirinaunimi reviewed
Thanks a lot @niclaurenti for this! I know that this is still in a draft mode but since we discussed this briefly I added some comments below.

2023-12-13 08:01 UTC, Radonirinaunimi commented on buildmaster/LHCB_WENU_8TEV/metadata.yaml
> +        operation: 'null'
If FK tables are not available, then you can for the time being remove this entry.
```suggestion

```

2023-12-13 15:51 UTC, niclaurenti commented on buildmaster/LHCB_WENU_8TEV/filter.py
> +        sys_beam.append(errors[idx]["errors"][2]["symerror"])
from this line
https://github.com/NNPDF/nnpdf/blob/f6b6c99bc28d1c8bdbd953d149feee79e91e1a00/buildmaster/filters/LHCB_WENU_8TEV.cc#L60
I assumed that the values stored in the rawdata folder (that is exactly what I implemented) are the absolute uncertainties

2023-12-14 15:26 UTC, Radonirinaunimi commented on buildmaster/LHCB_WENU_8TEV/filter.py
> +        sys_beam.append(errors[idx]["errors"][2]["symerror"])
You are absolutely right! I was comparing to a different table.

2023-12-15 12:02 UTC, Radonirinaunimi requested changes
Thanks again @niclaurenti for this! I've added a couple of corrections below.

I suggest to rename the dataset to be `LHCB_WPWM_8TEV_DILEPTON` in order to be confirm with the new naming conventions. Also, you should add the mapping from the old to the new name in `dataset_names.yml`:
```yaml
LHCB_WENU_8TEV_R: LHCB_WPWM_8TEV_DILEPTON
```

2024-07-17 14:47 UTC, scarlehoff commented
Missing: producing the grids and the fktables for these datasets

2024-11-14 10:30 UTC, closed without merging