[WIP] Reimplement ATLAS_Z0_7TEV_36PB Dataset
NNPDF/nnpdf pull request #2250
Opened 2024-12-18 11:41 UTC by ecole41

A function has been added to produce data.yaml file

[WIP] Still need to produce kinematics and uncertainties and run checks

2024-12-18 12:09 UTC, ecole41 commented on nnpdf_data/nnpdf_data/commondata/ATLAS_Z0_7TEV_36PB/metadata.yaml
> +    conversion_factor: 1.0187 #is this needed?
Same as for to WPWM dataset, I am not sure if this conversion factor is needed

2024-12-18 15:56 UTC, jacoterh commented
@ecole41 same comment as #2223 also applies here: please redo the report with the updated conversion factor taken into account. Looks good otherwise!

2024-12-18 15:57 UTC, jacoterh commented on nnpdf_data/nnpdf_data/commondata/ATLAS_Z0_7TEV_36PB/metadata.yaml
>    version: -1
Can be set to 1

2024-12-18 15:57 UTC, jacoterh commented on nnpdf_data/nnpdf_data/commondata/ATLAS_Z0_7TEV_36PB/metadata.yaml
>    url: ''
Please add the inspire link too

2025-01-21 10:44 UTC, scarlehoff requested changes
Just like in #2223, there's a factor of 10 missing in the luminosity uncertainty either in the new (*10) or in the old (1/10) data.

2025-01-21 10:44 UTC, scarlehoff commented on nnpdf_data/nnpdf_data/commondata/ATLAS_Z0_7TEV_36PB/metadata.yaml
> +        label: abs_eta
```suggestion
        label: "$y$"
```

Since it is rapidity and not pseudorapidity better to use `y`. At some point we were using eta/y to automatize a bit things (you can change also the `xlabel` to `$\left\| y\right|$` for instance) and so, some datasets that should be `Y` ended up being `ETA`. At some point I guess we'll update them.

2025-01-21 15:47 UTC, ecole41 commented on nnpdf_data/nnpdf_data/commondata/ATLAS_Z0_7TEV_36PB/metadata.yaml
> +        label: abs_eta
I have just updated this

2025-01-21 17:33 UTC, scarlehoff approved these changes

2025-01-21 17:33 UTC, scarlehoff commented on nnpdf_data/nnpdf_data/commondata/ATLAS_Z0_7TEV_36PB/metadata.yaml
> +        label: "$y$"
```suggestion
        label: "$|y|$"
```

2025-01-22 04:16 UTC, merged